version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
  api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  web:
    build: 
      context: ../WellVibeWebUI/
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ../WellVibeWebUI:/code/
    depends_on:
      - api